"Resource/UI/LoadoutPresetPanel.res"
{
	"loadout_preset_panel"
	{
		"ControlName"	"CLoadoutPresetPanel"
		"fieldName"		"loadout_preset_panel"
		"presetbutton_kv"
		{
			"zpos"			"20"
			"wide"			"25"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontMediumBold"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		""
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"centerwrap"	"1"
			"paintbackground"	"1"
			"defaultBgColor_override"	"DcMenuBut1"
			"armedBgColor_override"		"DcMenuBut2"
			"depressedBgColor_override"	"DcMenuBut1"
			"defaultFgColor_override"	"DcMenuFont1"
			"armedFgColor_override" 	"DcMenuFont2"
			"depressedFgColor_override" "DcMenuFont1"
			"border_default"			"DbMenuButton"
			"border_armed"				"DbMenuButton"
		}			
	}
}